// src/components/Calculus.svelte
<script lang="ts">
  const weightToString = (weight: number) => weight === 1 ? "" : weight === -1 ? "-" : weight.toFixed(3);

  type Props = {
    editMode: boolean;
    weights: number[];
    threshold: number;
    layer: number;
    changeWeight: (idx: number, val: number) => void;
    changeThreshold: (val: number) => void;
  }

  let { editMode, weights, threshold, layer, changeWeight, changeThreshold }: Props = $props();
</script>

{#snippet icon(i: number)}
  <div class="icon">
    <svg>
      <use href="#neuron-{i}" />
    </svg>
  </div>
{/snippet}

<div class="calculus">
  {#if editMode}
    <span>
      {#each weights as weight, i}
        {#if i > 0}
          <span class="plus">+</span>
        {/if}
        <span>
          <input
            class="input-number"
            type="number"
            value={weight}
            onchange={e => changeWeight(i, e.currentTarget.valueAsNumber)}
          />
          {@render icon((layer === 2 ? 6 : 0) + i)}
        </span>
      {/each}
    </span>
  {:else}
    <span>
      {#each weights as weight, i}
        {#if weight !== 0}
          {i > 0 && weight > 0 ? "+" : ""}
          {weightToString(weight)}
          {@render icon((layer === 2 ? 6 : 0) + i)}
        {/if}
      {/each}
    </span>
  {/if}
  <br/>
  Seuil:
  {#if !editMode}
    {threshold}
  {:else}
    <input
      class="input-number"
      type="number"
      value={threshold}
      onchange={e => changeThreshold(e.currentTarget.valueAsNumber)}
    />
  {/if}
</div>

<style>
  .calculus {
    font-size: 2.25rem;
    line-height: 2.5rem;
  }

  .icon {
    display: inline-block;
    width: 2rem;
    height: 2rem;
  }

  svg {
    width: 100%;
    height: 100%;
  }

  .plus {
    margin-left: 1rem;
    margin-right: 1rem;
  }
</style>

// src/components/Calculus.tsx
import { Component, Index, Match, Show, Switch } from "solid-js";

const weightToString = (weight: number) =>
  weight === 1 ? "" : weight === -1 ? "-" : weight.toFixed(3); 

type CalculusComponent = Component<{
  editMode: boolean,
  weights: number[],
  threshold: number,
  layer: number,
  changeWeight: (idx: number, val: number) => void
  changeThreshold: (val: number) => void
}>

const Calculus: CalculusComponent = props => (
  <div class="largetext">
    <Switch>
      <Match when={props.editMode}>
        <span>
          <Index each={props.weights}>
            {(weight, i) => (
              <>
                <Show when={i > 0}>
                  <span class="mx-4">+</span>
                </Show>
                <span>
                  <input
                    class="inputnumber"
                    type="number"
                    value={weight()}
                    onChange={e => props.changeWeight(i, e.currentTarget.valueAsNumber)}
                  />
                  <div class="inline-block w-8 h-8">
                    <svg class="w-full h-full">
                      <use href={`#neuron-${(props.layer === 2 ? 6 : 0) + i}`} />
                    </svg>
                  </div>
                </span>
                
              </>
            )}
          </Index>
        </span>
      </Match>
      <Match when={true}>
        <span>
          <Index each={props.weights}>
            {(weight, i) => (
              <Show when={weight() !== 0}>
                <>
                  {i > 0 && weight() > 0 ? "+" : ""}
                  {weightToString(weight())}
                  <div class="inline-block w-8 h-8">
                    <svg class="w-full h-full">
                      <use href={`#neuron-${(props.layer === 2 ? 6 : 0) + i}`} />
                    </svg>
                  </div>
                </>
              </Show>
            )}
          </Index>
        </span>
      </Match>
    </Switch>
    <br/>
    Seuil: 
    <Show when={props.editMode} fallback={""+props.threshold}>
      <input
        class="inputnumber"
        type="number"
        value={props.threshold}
        onChange={e => props.changeThreshold(e.currentTarget.valueAsNumber)}
      />
    </Show>
  </div> 
)

export default Calculus;
