// src/components/MiniPattern.svelte
<script lang="ts">
  import type { Pattern } from "../lib/model";
  const COLORS = ["var(--green-400)", "var(--blue-400)", "var(--pink-500)", "var(--yellow-400)"];

  type Props = {
    pattern: Pattern;
    isCurrent: boolean;
    onclick: () => void;
  }

  let { pattern, isCurrent, onclick}: Props = $props();
</script>

<button {onclick} class={isCurrent ? "current" : "notcurrent"}>
  {#each pattern.pattern as b, i}
    <div
      class="pixel"
      style:background-color={b ? COLORS[pattern.symbol] : "white"}
      style:left="{(i % 6) * 100 / 6}%"
      style:top="{(i / 6 | 0) * 100  / 9}%"
    ></div>
  {/each}
</button>

<style>
  button {
    overflow: hidden;
    position: relative;
    background-color: #ffffff;
    border: 4px solid #94a3b8;
    margin: 0.5rem;
    width: 5rem;
    height: 7.5rem;
    cursor: pointer;
  }

  .pixel {
    position: absolute;
    width: 16.66666666%;
    height: 11.1111111111%;
  }

  .current {
    border-color: var(--green-500);
  }

  .notcurrent {
    border-color: var(--slate-400);
  }
</style>

// src/components/MiniPattern.tsx
import { Component, Index, JSX } from "solid-js"
import { Pattern } from "../model"

const colors =  ["bg-green-400", "bg-blue-400", "bg-pink-500", "bg-yellow-400"]

type MiniPatternComponent = Component<{
  pattern: Pattern,
  isCurrent: boolean,
  onClick: JSX.EventHandlerUnion<HTMLDivElement, MouseEvent>
}>

const MiniPattern: MiniPatternComponent = props =>
  <div
    class="overflow-hidden relative bg-white border-4 border-slate-400 m-2 w-20 h-30 cursor-pointer"
    classList={{
      "border-green-500": props.isCurrent,  
      "border-slate-400": !props.isCurrent,
    }}
    onClick={props.onClick}
  >
   <Index each={props.pattern.pattern}>
    {((b, i) =>
      <div
        class={"absolute " + (b() ? colors[props.pattern.symbol] : "bg-white")}
        style={{
          width: "16.66666666%",
          height: "11.1111111111%",
          left: `${(i % 6) * 100 / 6}%`,
          top: `${(i / 6 | 0) * 100  / 9}%`,
        }}
      />
    )}
   </Index>
  </div>

export default MiniPattern;
