// src/components/NeuronDialog.svelte
<script lang="ts">
  import Ruler from "./Ruler.svelte";
  import type { Pattern, State } from "../lib/model";
  import Calculus from "./Calculus.svelte";

  const ALPHABET = "ABCDEF";
  const COLORS = ["vert", "bleu", "rose", "jaune"];

  type Props = {
    layer: number;
    idx: number;
    state: State;
    patterns: Pattern[];
    nbStates: number;
    stateIdx: number;
    learn: () => void;
    changeCurrentState: (i: number) => void;
    changeWeight: (layer: number, i: number, j: number, val: number) => void;
    changeThreshold: (layer: number, i: number, val: number) => void;
    closeDialog: () => void;
  }

  let { layer, idx, state: st, patterns, nbStates, stateIdx, learn,
    changeCurrentState, changeWeight, changeThreshold, closeDialog }: Props = $props();

  let editMode = $state(false);

  let title = $derived("Neurone " + (layer === 1 ? ALPHABET[idx] : COLORS[idx]))

  function edit() {
    editMode = !editMode;
  }
</script>

<div class="dialog-title">{title}</div>
<div class="dialog-body.flex.flex-col">
  <Calculus
    {layer}
    weights={layer === 1 ? st.hiddenWeights[idx] : st.finalWeights[idx]}
    threshold={layer === 1 ? st.hiddenThresholds[idx] : st.finalThresholds[idx]}
    {editMode}
    changeWeight={(k, val) => changeWeight(layer, idx, k, val)}
    changeThreshold={val => changeThreshold(layer, idx, val)}
  />
  <Ruler state={st} {patterns} {layer} {idx} small={false} />
  <div class="largetext">Nombre d'itérations: {st.iter}</div>
  {#if nbStates > 1}
    <input
      class="input-range range-lg"
      type="range"
      min="0"
      max={nbStates - 1}
      value={stateIdx}
      onchange={e => changeCurrentState(e.currentTarget.valueAsNumber)}
    />
  {/if}
</div>
<div class="dialog-buttons">
  <button class="btn" onclick={edit}>Editer</button>
  <button class="btn" onclick={learn}>Apprendre</button>
  <button class="btn" onclick={closeDialog}>OK</button>
</div>

// src/components/NeuronDialog.tsx
import { Component, createSignal, Index, Show } from "solid-js";
import Ruler from "./Ruler";
import { Pattern, State } from "../model";
import Calculus from "./Calculus";

const alphabet = "ABCDEF";
const colors = ["vert", "bleu", "rose", "jaune"];

const title = (layer: number, i: number) => "Neurone " + (layer === 1 ? alphabet[i] : colors[i]);

type NeuronComponent = Component<{
  layer: number,
  idx: number,
  state: State,
  patterns: Pattern[],
  nbStates: number,
  stateIdx: number,
  learn: () => void,
  changeCurrentState: (i: number) => void,
  changeWeight: (layer: number, i: number, j: number, val: number) => void,
  changeThreshold: (layer: number, i: number, val: number) => void,
  closeDialog: () => void,
}>

const NeuronDialog: NeuronComponent = props => {
  const [editMode, setEditMode] = createSignal(false);
  
  const edit = () => setEditMode(b => !b);

  return (
    <>
      <div class="dialog-title">{title(props.layer, props.idx)}</div>
      <div class="dialog-body flex flex-col">
        <Calculus
          layer={props.layer}
          weights={props.layer === 1 ? props.state.hiddenWeights[props.idx] : props.state.finalWeights[props.idx]}
          threshold={props.layer === 1 ? props.state.hiddenThresholds[props.idx] : props.state.finalThresholds[props.idx]}
          editMode={editMode()}
          changeWeight={(k, val) => props.changeWeight(props.layer, props.idx, k, val)}
          changeThreshold={val => props.changeThreshold(props.layer, props.idx, val)}
        />
        <Ruler
          state={props.state}
          patterns={props.patterns}
          layer={props.layer}
          idx={props.idx}
          small={false}
        />
        <div class="largetext">Nombre d'itérations: {props.state.iter}</div>
        <Show when={props.nbStates > 1}>
          <input
            class="inputrange range-lg"
            type="range"
            min="0"
            max={props.nbStates - 1}
            value={props.stateIdx}
            onChange={e => props.changeCurrentState(e.currentTarget.valueAsNumber)}
          />
        </Show>
      </div>
      <div class="dialog-buttons">
        <button class="btn" onClick={edit}>Editer</button>
        <button class="btn" onClick={props.learn}>Apprendre</button>
        <button class="btn" onClick={props.closeDialog}>OK</button>
      </div>
    </>
  )
}

export default NeuronDialog;
