// src/components/Pattern.tsx
import { Component, Index } from "solid-js"
import { Pattern } from "../model"

const colors = ["white", "black", "lightgreen", "darkgreen"];

type PatternComponent = Component<{
  selectedCaptor: number | null,
  pattern: Pattern,
  onClick: () => void,
}>

const PatternView: PatternComponent = props => (
  <div
    class="overflow-hidden relative border-4 border-slate-400 m-2 w-72 h-96 cursor-pointer"
    onClick={props.onClick}
  >
    <Index each={props.pattern.pattern}>
      {((b, i) => {
        const row = i / 6 | 0;
        const col = i % 6;
        const list: any[] = [(row / 3 | 0) + 3, col / 2 | 0];
        return (
          <div
            class="absolute pointer-events-none"
            style={{
              background: colors[Number(list.includes(props.selectedCaptor)) * 2 + Number(b())],
              width: "16.66666666%",
              height: "11.1111111111%",
              left: `${col * 100 / 6}%`,
              top: `${row * 100 / 9}%`,
            }}
          />
        )
      })}
    </Index>
  </div>
);

export default PatternView;

// src/components/Pattern.svelte
<script lang="ts">
  import { divMod } from "@gbagan/utils";
  import type { Pattern } from "../lib/model"
  
  const COLORS = ["white", "black", "lightgreen", "darkgreen"];
  
  type Props = {
    selectedCaptor: number | null;
    pattern: Pattern;
    onclick: () => void;
  };

  let { selectedCaptor, pattern, onclick }: Props = $props();
</script>

<button {onclick}>
  {#each pattern.pattern as b, i}
    {@const [row, col] = divMod(i, 6)}
    {@const list = [(row / 3 | 0) + 3, col / 2 | 0]}
    {@const color = COLORS[Number(list.includes(selectedCaptor ?? -1)) * 2 + Number(b)]}
    <div
      class="pixel"
      style:background={color}
      style:left="{col * 100 / 6}%"
      style:top="{row * 100 / 9}%"
    ></div>
  {/each}
</button>

<style>
  button {
    overflow: hidden;
    position: relative;
    border: 4px solid var(--slate-400);
    margin: 0.5rem;
    width: 18rem;
    height: 24rem;
    cursor: pointer;
  }

  .pixel {
    position: absolute;
    pointer-events: none;
    width: 16.66666666%;
    height: 11.1111111111%;
  }
</style>
