// src/App.tsx
import { Component, Match, Switch, batch } from 'solid-js';
import { createStore, produce } from "solid-js/store";
import { initModel, initPatterns, NDialog, updateInput, updateOutput } from './model';
import { runLearning } from './learn';
import PatternView from './components/Pattern';
import Network from './components/Network';
import Editor from './components/Editor';
import AllNeuronsDialog from './components/AllNeuronsDialog';
import NeuronDialog from './components/NeuronDialog';
import { delay } from './util';

const App: Component = () => {
  const [model, setModel] = createStore(initModel());
  let dialog: HTMLDialogElement;

  const output = () => model.states[model.currentState].output;
  const final = () => output()[model.currentPattern].final;

  const simulate = () => {
    setModel(produce(model => {
      model.inputs = updateInput(model.patterns);
      for (const st of model.states) {
        st.output = updateOutput(model.inputs, st);
      }
    }))
  }

  simulate();

  const keepOneState = () => {
    setModel("states", [model.states[model.currentState]]);
    setModel("states", 0, "iter", 0);
    setModel("currentState", 0);
  }

  const openEditorDialog = () => {
    setModel("dialog", {type: "edit"});
    dialog.showModal();
  }

  const openAllNeuronsDialog = () => {
    setModel("dialog", {type: "neurons"});
    dialog.showModal();
  }

  const openNeuronDialog = (layer: number, idx: number) => {
    setModel("dialog", {type: "neuron", layer, idx});
    dialog.showModal();
  }

  const closeDialog = () => {
    setModel("dialog", {type :"none"});
    dialog.close();
  }

  const selectInput = (i: number | null) => setModel("selectedInput", i);
  const togglePattern = (i: number) => setModel("patterns", i, "selected", b => !b);
  const setCurrentPattern = (i: number) => setModel("currentPattern", i);
  const previousPattern = () => setModel("currentPattern", i => (i + 23) % 24)
  const nextPattern = () => setModel("currentPattern", i => (i + 1) % 24)

  const changePixel = (i: number) => {
    batch(() => {
      setModel("patterns", model.currentPattern, "pattern", i, b => !b);
      simulate();
    })
  }

  const resetPatterns = () => {
    batch(() => {
      setModel("patterns", initPatterns());
      simulate();
    })
  }

  const changeWeight = (layer: number, i: number, j: number, val: number) => {
    batch(() => {
      setModel("states", model.currentState, layer === 1 ? "hiddenWeights" : "finalWeights", i, j, val);
      keepOneState();
      simulate();
    });
  }

  const changeThreshold = (layer: number, i: number, val: number) => {
    batch(() => {
      setModel("states", model.currentState, layer === 1 ? "hiddenThresholds" : "finalThresholds", i, val);
      keepOneState();
      simulate();
    });
  }

  const learn = () => setModel("states", runLearning(model));

  const changeCurrentState = (i: number) => setModel("currentState", i);

  const reset = () => {
    batch(() => {
      setModel(initModel());
      simulate();
    })
  }

  const runSimulation = async () => {
    const n = model.states.length;
    for (let i = 0; i < n; i++) {
      setModel("currentState", i);
      await delay(1500);
    }
  }

  const editorActions = {
    setCurrentPattern,
    changePixel,
    closeDialog,
    togglePattern,
    resetPatterns,
  }

  const networkActions = {
    selectInput,
    openNeuronDialog
  }

  const neuronDialogActions = {
    learn,
    changeCurrentState,
    changeThreshold,
    changeWeight,
    closeDialog,
  }

  const allNeuronsActions = {
    learn,
    changeCurrentState,
    runSimulation,
    closeDialog,
  }

  return (
    <>
      <div class="w-full min-h-screen bg-black flex flew-row items-center justify-around portrait:flex-col">
        <div class="flex flex-col items-center portrait:flex-row">
          <PatternView
            selectedCaptor={model.selectedInput}
            pattern={model.patterns[model.currentPattern]}
            onClick={openEditorDialog}
          />
          <div class="grid grid-cols-2 gap-1">
            <button class="btn" onClick={previousPattern}>Précédent</button>
            <button class="btn" onClick={nextPattern}>Suivant</button>
            <button class="btn" onClick={openAllNeuronsDialog}>Réglettes</button>
            <button class="btn" onClick={reset}>Réinitialiser</button>
          </div>      
        </div>
        <div class="w-2/3 portrait:w-full">
          <Network final={final()} {...networkActions} />
        </div>
      </div>
      <dialog class="dialog" ref={el => (dialog = el)}>
        <Switch>
          <Match when={model.dialog.type === "edit"}>
            <Editor
              patterns={model.patterns}
              currentPattern={model.currentPattern}
              {...editorActions}
            />
          </Match>
          <Match when={model.dialog.type === "neurons"}>
            <AllNeuronsDialog
              state={model.states[model.currentState]}
              patterns={model.patterns}
              nbStates={model.states.length}
              stateIdx={model.currentState}
              {...allNeuronsActions}
            />
          </Match>
          <Match when={model.dialog.type === "neuron"}>
            <NeuronDialog
              layer={(model.dialog as NDialog).layer}
              idx={(model.dialog as NDialog).idx}
              state={model.states[model.currentState]}
              patterns={model.patterns}
              nbStates={model.states.length}
              stateIdx={model.currentState}
              {...neuronDialogActions}
            />
          </Match>
        </Switch>
      </dialog>
    </>
  )
}

export default App;

// src/App.svelte
<script lang="ts">
  import { update } from './lib/util';
  import { sleep } from '@gbagan/utils';
  import { type Dialog, initPatterns, initState, type NDialog, type State, updateInput, updateOutput } from './lib/model';
  import { runLearning } from './lib/learn';
  import PatternView from './components/Pattern.svelte';
  import Network from './components/Network.svelte';
  import Editor from './components/Editor.svelte';
  import AllNeuronsDialog from './components/AllNeuronsDialog.svelte';
  import NeuronDialog from './components/NeuronDialog.svelte';

  let patterns = $state.raw(initPatterns);
  let inputs: number[][] = $state.raw([]);
  let states: State[] = $state.raw([initState]);
  let currentState = $state(0);
  let currentPattern = $state(0);
  let selectedInput: number | null = $state(null);
  let editMode = $state(false);
  let dialog: Dialog = $state.raw({ type: "none" });

  let dialogEl!: HTMLDialogElement;

  let output = $derived(states[currentState].output);
  let final = $derived(output[currentPattern].final);

  function simulate() {
    inputs = updateInput(patterns);
    states = states.map(st => ({...st, output: updateOutput(inputs, st)}));
  }

  simulate();

  function keepOneState() {
    let newState = states[currentState];
    newState = {...newState, iter: 0};
    states = [newState];
    currentState = 0;
  }

  function openEditorDialog() {
    dialog = {type: "edit"};
    dialogEl.showModal()
  }

  function openAllNeuronsDialog() {
    dialog = {type: "neurons"};
    dialogEl.showModal();
  }

  function openNeuronDialog(layer: number, idx: number) {
    dialog = {type: "neuron", layer, idx};
    dialogEl.showModal();
  }

  function closeDialog() {
    dialog = { type: "none" };
    dialogEl.close();
  }

  function selectInput(i: number | null) {
    selectedInput = i;
  }

  function togglePattern(i: number) {
    patterns = update(patterns, [i, "selected"], x => !x); 
  }
  
  function setCurrentPattern(i: number) {
    currentPattern = i;
  }

  function previousPattern() {
    currentPattern = (currentPattern + 23) % 24;
  }
  
  function nextPattern() {
    currentPattern = (currentPattern + 1) % 24;
  }

  function changePixel(i: number) {
    patterns = update(patterns, [currentPattern, "pattern", i], x => !x);
    simulate()
  }

  function resetPatterns() {
    patterns = initPatterns;
    simulate();
  }

  function changeWeight(layer: number, i: number, j: number, val: number) {
    states = update(states, [currentState, layer === 1 ? "hiddenWeights" : "finalWeights", i, j], () => val);
    keepOneState();
    simulate();
  }

  function changeThreshold(layer: number, i: number, val: number) {
    states = update(states, [currentState, layer === 1 ? "hiddenThresholds" : "finalThresholds", i], () => val);
    keepOneState();
    simulate();
  }

  function learn() {
    states = runLearning(inputs, states[0], patterns);
  }

  function changeCurrentState(i :number) {
    currentState = i;
  }

  function reset() {
    patterns = initPatterns;
    inputs = [];
    states = [initState];
    currentState = 0;
    currentPattern = 0;
    selectedInput = null;
    editMode = false;
    dialog = { type: "none" };
    simulate();
  }

  async function runSimulation() {
    const n = states.length;
    for (let i = 0; i < n; i++) {
      currentState = i;
      await sleep(1500);
    }
  }
</script>

<div class="app">
  <aside>
    <PatternView
      selectedCaptor={selectedInput}
      pattern={patterns[currentPattern]}
      onclick={openEditorDialog}
    />
    <div class="buttons">
      <button class="btn" onclick={previousPattern}>Précédent</button>
      <button class="btn" onclick={nextPattern}>Suivant</button>
      <button class="btn" onclick={openAllNeuronsDialog}>Réglettes</button>
      <button class="btn" onclick={reset}>Réinitialiser</button>
    </div>
  </aside>
  <main>
    <Network {final} {selectInput} {openNeuronDialog} />
  </main>
</div>
  
<dialog class="dialog" bind:this={dialogEl}>
  {#if dialog.type === "edit"}
    <Editor {patterns} {currentPattern} 
      {setCurrentPattern} {changePixel} {closeDialog} {togglePattern} {resetPatterns}
    />
  {:else if dialog.type === "neurons"}
    <AllNeuronsDialog
      state={states[currentState]}
      {patterns}
      nbStates={states.length}
      stateIdx={currentState}
      {learn}
      {changeCurrentState}
      {runSimulation}
      {closeDialog}
    />
  {:else if dialog.type === "neuron"}
    <NeuronDialog
      layer={dialog.layer}
      idx={dialog.idx}
      state={states[currentState]}
      {patterns}
      nbStates={states.length}
      stateIdx={currentState}
      {learn}
      {changeCurrentState}
      {changeThreshold}
      {changeWeight}
      {closeDialog}
    />
  {/if}
</dialog>

<style>
  .app {
    width: 100%;
    min-height: 100vh;
    background-color: var(--gray-900);
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-around;
  }

  aside {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  main {
    width: 66.666667%;
  }

  @media (orientation: portrait) {
    .app {
      flex-direction: column;
    }

    aside {
      flex-direction: row;
    }

    main {
      width: 100%;
    }
  }

  .buttons {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 0.25rem;
  }
</style>
